spring:
  application:
    name: pome-server
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true

  datasource:
    url: ENC(UhTZCchsTuaeCIIRGVB6fspHO4hHAO93iN26ywQqRZ50Jt2SMHuqnGRZTh1cpTP549QnZTp6h9SO3x/sGlMvvS0X2h8o9ILPJcDspScRnXxdsY+b6U3IyiBfcnPgWnb2)
    username: ENC(Nuj++ONTcU4Eni1u8DZUtg==)
    password: ENC(gUg4tCfrFn1uhFANXIwld0OgbavZq0zQzrT1sgXY5fY=)
    driver-class-name: org.mariadb.jdbc.Driver

  redis:
    host: ENC(A8Kbxf7WkyJXcjNIGNBBbFWLt3AboErqoV3FfEZbQSw5YZ9J6SiTZWmPlvaeM/IDVHO6SxD3l9d7qun3UTxtWQ==)
    port: 6379

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    pool-size: 2
    string-output-type: base64
    key-obtention-iterations: 100000
#    password: password

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

  metrics:
    tags:
      application: ${spring.application.name}

---
spring:
  profiles:
    active: prod
---
spring:
  profiles:
    active: dev


