spring:
  application:
    name: pome-server
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true

  datasource:
    url: ENC(/senGpUtjiUUOHFhiF1GVqgq+5FM9uXefgbdKJ+wUkkmtPVqwKk5i5XfT0EW7MdD8VTVm9Q7aZBiFNyM8DGkICiOVcHaHpNrdwgxdlhDv2oJs6e2Fng6JNNjHsacFP9S)
    username: ENC(IYzvRWBhSVqPTiMmHrcbbA==)
    password: ENC(krxh0bWdOGwi1Cb1Lv+0eQQnncteJAaEZgBzLEykHyw=)
    driver-class-name: org.mariadb.jdbc.Driver

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    pool-size: 2
    string-output-type: base64
    key-obtention-iterations: 100000
#    password: password

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

  metrics:
    tags:
      application: ${spring.application.name}

