spring:
  application:
    name: pome-server

  profiles:
    include:
      secret

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true

  datasource:
    url: ENC(UhTZCchsTuaeCIIRGVB6fspHO4hHAO93iN26ywQqRZ50Jt2SMHuqnGRZTh1cpTP549QnZTp6h9SO3x/sGlMvvS0X2h8o9ILPJcDspScRnXxdsY+b6U3IyiBfcnPgWnb2)
    username: ENC(Nuj++ONTcU4Eni1u8DZUtg==)
    password: ENC(gUg4tCfrFn1uhFANXIwld0OgbavZq0zQzrT1sgXY5fY=)
    driver-class-name: org.mariadb.jdbc.Driver

  redis:
    host: ENC(dqWGAouH23IUMTg7tXQ8Xti271oGEUop)
    port: 6379

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    pool-size: 2
    string-output-type: base64
    key-obtention-iterations: 100000
#    password: password

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

  metrics:
    tags:
      application: ${spring.application.name}

sms:
  service-id: ENC(jRcp9bJ+pmP5Chc7PjdXvOO0G7zA+bMRVogojNPNqp5zMpHZEG4XGYW0hr09rZW6)
  access-key: ENC(RUDLHvlS4pyljqRnVLtcij1/laYT3SmVAzYRsPrBmdY=)
  secret-key: ENC(m4bqtTEsHWdFabh0qVqyunARg1Qm+r9v9N9TVrz+9RnTJoGMFjE+YloqOVaK+hiQuGTZ9Hvs1PI=)
  phone-num: ENC(42M3V/I2lZaJJ/mF4vfW1L3HBpykydka)

jwt:
  secret: ENC(kFyergO+nlIqq0vnPfSKdDCewKTDZAY2)
  token-type: ENC(kB4scBl7UZNs7D4+oQS0kA==)
  access-header: ENC(YVcSaDhY0eW9ptAstEkB2cO3WgvumW8S)
  refresh-header: ENC(PLjwqyNhcZtPwz+nHi33M9E3avnatw20)
  access-expired-time: ENC(ta72CBPrazeD/2eL5P+v9w==)          # 20분
  refresh-expired-time: ENC(wKNz85sWCuHRpaMjtJVwbUX+9XCWEkkh) # 약 30일

---
spring:
  profiles:
    active: prod
---
spring:
  profiles:
    active: dev


